# Generated by Django 4.2.1 on 2023-05-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_department_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
